### ISSUE TITLE
file go.mod

### ISSUE THREAD

**Issue by andreluna** [optiv/Mangle#1]
Hi man,
You not insert go.mod file in project.

**Comment by andreluna** [comment]
To solved I did:

`git clone git@github.com:optiv/Mangle.git
cd Mangle

go mod init github.com/optiv/Mangle
go get github.com/Binject/debug/pe
go build Mangle.go`

**Comment by Tylous** [comment]
you shouldn't need a mod file. 
![image](https://user-images.githubusercontent.com/15052743/175366109-23d0bfc6-023f-4186-9a28-d35122d1691f.png)

**Comment by andreluna** [comment]
Okay! Thks.
