### ISSUE TITLE
Only Error: Please provide a path to a file you wish to mangle

### ISSUE THREAD

**Issue by diogomaia33** [optiv/Mangle#7]
D:\NoScan\Mangle\Mangle>Mangle.exe -S 100 test.exe

           _____                        .__
          /     \ _____    ____    ____ |  |   ____
         /  \ /  \\__  \  /    \  / ___\|  | _/ __ \
        /    Y    \/ __ \|   |  \/ /_/  >  |_\  ___/
        \____|__  (____  /___|  /\___  /|____/\___  >
                \/     \/     \//_____/           \/
                                        (@Tyl0us)
2022/07/19 20:52:32 Error: Please provide a path to a file you wish to mangle

**Comment by Tylous** [comment]
your missing the -I and -O flag. Please check the README file or the -h command for more information.
